spring:
  application:
    name: one-one
  datasource:
    url: jdbc:mysql://localhost:3306/one-one-qa
    username: root
    password: 8610425056aA@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQLDialect
  sleuth:
    sampler:
      probability: 1.0 # Ensures all traces are sampled (100%)
  zipkin:
    base-url: http://localhost:9411 # URL where Zipkin is running      
