spring:
  application:
    name: one-one

  datasource:
    url: jdbc:mysql://localhost:3306/one-one-prod
    username: root
    password: 8610425056aA@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQLDialect
